# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9635f5837357dac8c2378a4391adb97498b00ef3acbc791de687b6dc48fe01a803cdb5019853c934ad7ee6f71132496e2e5cabc74dbf83a6f15e34f23a5d972c

test:
  secret_key_base: 1ca1c9c6321d14ee25766da3477c2db4fe480c5a76b60949ea10b1adf210c59896bb331cd4d6f190e095ad06a1a3760f7da0209c711135253f8878e7a0676333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
